version: '3.7'

services:
  db:
    image: postgres
    env_file:
      - .dockerenv
    volumes:
      - ./pgdata:/opt/postgresql/data
    ports:
      - 7200:5432

  pg_admin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/opt/pgadmin
    links:
      - "db:pgsql-server"

